<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2011-10-04 12:09

$extensionPath = t3lib_extMgm::extPath('aloha');
$extensionClassesPath = t3lib_extMgm::extPath('aloha') . 'Classes/';
return array(
	'tx_aloha_aloha_integration' => $extensionClassesPath . 'Aloha/Integration.php',
	'tx_aloha_aloha_save' => $extensionClassesPath . 'Aloha/Save.php',
	'tx_aloha_browselink_content' => $extensionClassesPath . 'BrowseLink/Content.php',
	'tx_aloha_browselink_index' => $extensionClassesPath . 'BrowseLink/index.php',
	'tx_aloha_hooks_adminpanel' => $extensionClassesPath . 'Hooks/Adminpanel.php',
	'tx_aloha_hooks_contentpostproc' => $extensionClassesPath . 'Hooks/ContentPostProc.php',
	'tx_aloha_hooks_editicons' => $extensionClassesPath . 'Hooks/EditIcons.php',
	'tx_aloha_hooks_requestpreprocess_cebullets' => $extensionClassesPath . 'Hooks/RequestPreProcess/CeBullets.php',
	'tx_aloha_hooks_requestpreprocess_cetable' => $extensionClassesPath . 'Hooks/RequestPreProcess/CeTable.php',
	'tx_aloha_hooks_requestpreprocess_cleanup' => $extensionClassesPath . 'Hooks/RequestPreProcess/Cleanup.php',
	'tx_aloha_interfaces_requestpreprocess' => $extensionClassesPath . 'Interfaces/RequestPreProcess.php',
	'tx_aloha_interfaces_toolbarpostprocess' => $extensionClassesPath . 'Interfaces/ToolbarPostProcess.php',
	'tx_aloha_utility_access' => $extensionClassesPath . 'Utility/Access.php',
	'tx_aloha_utility_helper' => $extensionClassesPath . 'Utility/Helper.php',
	'tx_aloha_utility_integration' => $extensionClassesPath . 'Utility/Integration.php',
	'tx_aloha_viewhelpers_editableviewhelper' => $extensionClassesPath . 'ViewHelpers/EditableViewHelper.php',
);
?>